name: Build & Deploy

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}     # e.g. ghcr.io/jake0lawrence/writebook

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write     # push to GHCR

    steps:
      - uses: actions/checkout@v4

      # ── login to GHCR ─────────────────────────────
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ── login to ONCE registry ───────────────────
      - name: Log in to ONCE registry
        uses: docker/login-action@v3
        with:
          registry: registry.once.com
          username: ${{ secrets.ONCE_TOKEN }}
          password: ${{ secrets.ONCE_TOKEN }}

      # ── build & push image ───────────────────────
      - name: Build image
        run: |
          docker build \
            --build-arg SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} \
            -t $IMAGE_NAME:${{ github.sha }} .
      - name: Push image
        run: docker push $IMAGE_NAME:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Pull & restart on droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull $IMAGE_NAME:${{ github.sha }}
            docker tag  $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
            cd /opt/once/current    # adjust if your compose file lives elsewhere
            docker compose up -d
            echo "✅ Deployed $IMAGE_NAME:${{ github.sha }}"
