name: Lint & Unit-Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ── Node / JS/TS ────────────────────────────────
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: |
          npm ci
          npm run lint        # eslint / prettier
          npm test || true    # optional jest / vitest

      # ── Shell scripts (ShellCheck) ─────────────────
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@v2.0.0   # ← stable tag
        with: { severity: warning }

      # ── Python (optional) ──────────────────────────
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: |
          pip install pytest
          pytest || true       # run only if tests present
